### ISSUE TITLE
파이썬 4주차 과제 제출

### ISSUE THREAD

**Issue by ChoiKangM** [haedal-with-knu/theBeginingOfPython#20]
플라스크로 웹서버 띄우시고,
"학번, 학과, 이름" 쓰신 웹페이지를 화면캡쳐해 사진 올려주세요 :)

**Comment by JiJeuwa** [comment]
![haedal](https://user-images.githubusercontent.com/65893099/84576456-da54c900-adef-11ea-8fa8-3b8875befb1b.PNG)

**Comment by oyoungsun** [comment]
<img width="1278" alt="준회원 4주차 파이썬 과제 - 오영선" src="https://user-images.githubusercontent.com/63745627/86091994-c5fb1680-bae7-11ea-91b3-ca4090ac6209.png">
.

**Comment by impulsive526** [comment]
<img width="969" alt="스크린샷 2020-06-30 오후 4 12 44" src="https://user-images.githubusercontent.com/67626880/86095555-0c9f3f80-baed-11ea-9cad-22a57761d2d5.png">

**Comment by dack-c** [comment]
![캡처](https://user-images.githubusercontent.com/56577363/86108443-1e3d1300-bafe-11ea-8aa3-20f819f1d2e1.JPG)

**Comment by bgainal** [comment]
![과제](https://user-images.githubusercontent.com/67634450/86114724-e76afb00-bb05-11ea-8bd4-90d19998ae3d.png)

**Comment by dhraudwn** [comment]
![캡처](https://user-images.githubusercontent.com/62053412/86240779-c5907780-bbdc-11ea-95da-b28d1a43f116.PNG)

**Comment by jypkec** [comment]
![image](https://user-images.githubusercontent.com/67785034/86458590-6eb3ab00-bd60-11ea-9ed3-83c5d092730f.png)

**Comment by jaesseong** [comment]
![스크린샷(2)](https://user-images.githubusercontent.com/62880445/86472264-db876f00-bd79-11ea-905f-2a2ae1637de6.png)

**Comment by lsin07** [comment]
![image](https://user-images.githubusercontent.com/67792371/86474289-76ce1380-bd7d-11ea-969e-98da29099389.png)

**Comment by SEIN126** [comment]
<img width="960" alt="1" src="https://user-images.githubusercontent.com/53332252/86506572-7a0fe080-be0b-11ea-8956-1081532e4ded.png">

**Comment by JaeJeongHwang** [comment]
![image](https://user-images.githubusercontent.com/67818986/86507129-995d3c80-be10-11ea-98b5-aee50515b58a.png)

**Comment by johm3801** [comment]
![image](https://user-images.githubusercontent.com/67828575/86512442-4ea5e980-be3d-11ea-8f69-01f03006b549.png)

**Comment by jeongmin01** [comment]
http://127.0.0.1:5000/

**Comment by jeongmin01** [comment]
![image](https://user-images.githubusercontent.com/67833403/86515298-d813e680-be52-11ea-8082-5fd31b292001.png)

**Comment by Kim-Jiwan** [comment]
![image](https://user-images.githubusercontent.com/65444464/86516038-70609a00-be58-11ea-8d5d-4d3b0c3adf10.png)

**Comment by jijun0129** [comment]
![해달 과제](https://user-images.githubusercontent.com/67828536/86519124-b62a5c00-be72-11ea-8de9-c35aabda2d72.png)

**Comment by kimjea1999** [comment]
![SCR1](https://user-images.githubusercontent.com/62633712/102459023-6ccc7280-4088-11eb-9507-6c484e116f97.png)

**Comment by Qad00** [comment]
![Uploading SmartSelectImage_2020-12-17-20-39-31.png…]()

**Comment by Qad00** [comment]
![SmartSelectImage_2020-12-17-20-39-31](https://user-images.githubusercontent.com/68487045/102483717-7c5bb380-40a8-11eb-8c15-ec40b8a89f13.png)
