### ISSUE TITLE
2020 2학기 파이썬 2주차 과제 제출

### ISSUE THREAD

**Issue by ewsn1593** [haedal-with-knu/theBeginingOfPython#25]
댓글로 자기 학번, 학과, 이름 그리고 깃헙 레포 주소를 올려주시면 됩니다 :)
 EX )  2017110887 전자공학부 신준철 2주차 과제 제출입니다 https://github.com/ewsn1593/Practice

**Comment by m1-oh** [comment]
2017112219 전자공학부 오명원 2주차 과제 제출입니다 https://github.com/m1-oh/Homework

**Comment by chadata** [comment]
2018113598 모바일공학과 차민준 2주차 과제 제출입니다. https://github.com/chadata/practice

**Comment by DonggyuL** [comment]
2020112773 전자공학부 이동규 2주차 과제 제출입니다. https://github.com/DonggyuL/-1

**Comment by chs3421** [comment]
2019110785 전기공학과 김민지 2주차 과제 제출입니다 https://github.com/chs3421/22222

**Comment by himodu** [comment]
2020112267 컴퓨터학부 이동건 2주차 과제 제출입니다. https://github.com/himodu/Practice.git

**Comment by donghy22** [comment]
2015115781 경제통상학부 이동현 2주차 과제 제출입니다. https://github.com/donghy22/Practice

**Comment by Qad00** [comment]
2020111177 컴퓨터학부 이동건 2주차 과제 제출입니다.https://github.com/Qad00/HaedalHW.git

**Comment by Qad00** [comment]
2020111177 컴퓨터학부 카드리딘 2주차 과제 제출입니다.https://github.com/Qad00/HaedalHW.git

**Comment by chs3421** [comment]
2019110785 전기공학과 김민지 2주차 과제 제출입니다 https://github.com/chs3421/22222

**Comment by 52future** [comment]
2020113825학번 컴퓨터학부 손자영 2주차 과제 제출입니다. https://github.com/52future/gitpractice1.git

**Comment by Jung-Jaemin** [comment]
2016116453 전자공학부 정재민 2주차 과제 제출입니다. https://github.com/jjm5811/Practice

**Comment by boksuh** [comment]
2017115698 전자공학부 서보경 2주차 과제 제출입니다. https://github.com/boksuh/HW

**Comment by apple0626** [comment]
2018112277 컴퓨터학부 김현진 2주차 과제 제출입니다. https://github.com/apple0626/Web_programming

**Comment by hdddhdd** [comment]
2020114670 컴퓨터학부 최희정 2주차 과제 제출입니다. https://github.com/hdddhdd/Playlist

**Comment by iougou03** [comment]
2017116948 컴퓨터학부 권해솔 2주차 과제 제출입니다.  https://github.com/iougou03/Python-HaeDal

**Comment by kiryanchi** [comment]
2017112387 전자공학부 박기현 2주차 과제 제출입니다. https://github.com/kiryanchi/Haedal_Practice

**Comment by JMK1007** [comment]
2018117628 컴퓨터학부 김지민 2주차 과제 제출입니다. https://github.com/JMK1007/practice

**Comment by penguin123-pi** [comment]
2019113608 전자공학부 이현중 2주차 과제 제출입니다. https://github.com/penguin123-pi/practice

**Comment by poseriang** [comment]
2020115194 전자공학부 민주호 2주차 과제 제출입니다. https://github.com/poseriang/haedalhomework

**Comment by swimmmmie** [comment]
2019110667 컴퓨터학부 김수영 2주차 과제 제출입니다. https://github.com/swimmmmie/prac1

**Comment by kimjea1999** [comment]
2019111569 컴퓨터학부 김지은 2주차 과제 제출입니다. https://github.com/kimjea1999/Haedal_Work

**Comment by gyeongpyo** [comment]
2018117630 컴퓨터학부 옥경표 2주차 과제 제출입니다. https://github.com/gyeongpyo/practice/blob/master/python/w2.md

**Comment by jeonghyeon1120** [comment]
2019116357 전자공학부 나정현 2주차 과제 제출입니다. https://github.com/jeonghyeon1120/homework1

**Comment by truegeonshow** [comment]
2018117818 경영학부 김건희 2주차 과제 제출입니다. https://github.com/truegeonshow/practice/blob/master/1README.md

**Comment by choimyungbin** [comment]
2020111799 최명빈 2주차 과제 제출합니다. https://github.com/choimyungbin/Practice/tree/master/venv

**Comment by bgainal** [comment]
2020111485 전자공학부 신영진 2주차 과제 제출합니다. https://github.com/bgainal/practice/blob/master/README.md

**Comment by Sungbinbinbin** [comment]
2020114669 전자공학부 조성빈 2주차 과제 제출합니다.
https://github.com/Sungbinbinbin/python-practice

**Comment by packsooan** [comment]
2020113105 전자공학부 백수안 2주차 과제 제출합니다 
https://github.com/packsooan/practice/blob/master/README.md

**Comment by ImNotJSW** [comment]
2019115817 컴퓨터학부 장성욱 2주차 과제 제출합니다. https://github.com/ImNotJSW/Homework/blob/master/GitInstructions.md

**Comment by ftlghk** [comment]
2020111501 전자공학부 류시화 2주차 과제 제출합니다.
https://github.com/ftlghk/Practice

**Comment by kimhj98** [comment]
2017110092 전자공학부 김현준 2주차 과제 제출합니다.
https://github.com/kimhj98/HW1.git

**Comment by baha1909** [comment]
2020116142 모바일공학과 최인표 2주차 과제 제출하겠습니다.
https://github.com/baha1909/Second

**Comment by yanghuijin1214** [comment]
2018111062 컴퓨터학부 양희진 2주차 과제 제출입니다.
https://github.com/haedal-with-knu/theBeginingOfPython/issues/25

**Comment by yanghuijin1214** [comment]
2018111062 컴퓨터학부 양희진 2주차 과제 제출입니다. https://github.com/yanghuijin1214/practice2

**Comment by yanghuijin1214** [comment]
2018111062 컴퓨터학부 양희진 2주차 과제 제출입니다. https://github.com/yanghuijin1214/practice2

**Comment by JoDongHyuen** [comment]
2017111705 컴퓨터학부 조동현 2주차 과제 제출합니다. https://github.com/JoDongHyuen/Practice

**Comment by flwhdgur** [comment]
2017110615 임산공학과 이종혁 2주차 과제입니다. https://github.com/jonghyeok-1/practice/blob/master/MIDTERM.md

**Comment by cyj-aws** [comment]
2020111367 전자공학부 진채영 2주차 과제 제출입니다 https://github.com/cyj-aws/Practice

**Comment by hyeongjong98** [comment]
2017116463 임산공학과 이형종 2주차 과제입니다. https://github.com/hyeongjong98/goom/blob/master/GOOMTOE.md

**Comment by sseo512** [comment]
2019111509 전자공학부 서혜원 2주차 과제 제출입니다. https://github.com/sseo512/HAEDAL-week2

**Comment by MyNameIsTaeYeong** [comment]
2018117677 전자공학부 임태영 2주차 과제 제출입니다. https://github.com/MyNameIsTaeYeong/Practice_python/blob/master/README.md

**Comment by sweetiewetie** [comment]
2017116953 심리정보융합전공 김소연 2주차 과제 제출입니다 https://github.com/sweetiewetie/HW1

**Comment by yxxniverse** [comment]
2019113288 컴퓨터학부 서정윤 2주차 과제 제출입니다 https://github.com/yxxniverse/practice

**Comment by ezzez** [comment]
2020112393 컴퓨터학부 김은정 2주차 과제제출입니다.
https://github.com/ezzez/headal_py

**Comment by kayoung0** [comment]
2019113963 컴퓨터학부 김가영 2주차 과제입니다.
https://github.com/kayoung0/haedal-python/tree/master

**Comment by pavk96** [comment]
2015117254 독어독문학과 박규정 2주차 과제입니다.
https://github.com/pavk96/Practice.git

**Comment by yeji-jeong** [comment]
2019110481 전자공학부 정예지 2주차 과제입니다.
https://github.com/yeji-jeong/practice/blob/master/README.md

**Comment by kitae0** [comment]
2020114217 전자공학부 김기태 2주차 과제입니다.
https://github.com/kitae0/practice

**Comment by seongjin22** [comment]
2017111400 전자공학부 손성진 2주차 과제입니다.
https://github.com/seongjin22/Practice

**Comment by hai-ley** [comment]
2020111179 전자공학부 장혜원 2주차 과제입니다.
https://github.com/hai-ley/Practice/blob/master/REAEME.md
