### ISSUE TITLE
2020 2학기 파이썬 3주차 과제 제출

### ISSUE THREAD

**Issue by johm3801** [haedal-with-knu/theBeginingOfPython#26]
댓글로 자기 학번, 학과, 이름 그리고 스크린샷(직접 짠 코드와 인스턴스 추가하는 함수를 사용했을 때의 결과가 나타나도록) 업로드 해주시면 됩니다!

**Comment by chadata** [comment]
![HW3](https://user-images.githubusercontent.com/71762438/95976901-1c9c1e80-0e53-11eb-927a-8fdc3b71c678.JPG)

**Comment by chadata** [comment]
![HW33](https://user-images.githubusercontent.com/71762438/95978298-ee1f4300-0e54-11eb-9061-ff5998c263e1.JPG)
2018113598 모바일공학과 차민준

**Comment by 52future** [comment]
2020113825 컴퓨터학부 손자영
![스크린샷 2020-10-18 13 49 55](https://user-images.githubusercontent.com/68419721/96359114-d80dcd00-1149-11eb-9564-77b5ab9de159.png)

**Comment by JMK1007** [comment]
![3주차](https://user-images.githubusercontent.com/67947887/97268348-1d7b7a00-186f-11eb-8d60-421f1ee743e4.png)
2018117628 컴퓨터학부 김지민

**Comment by truegeonshow** [comment]
![image](https://user-images.githubusercontent.com/71762698/97275245-093c7a80-1879-11eb-9c15-11effc657e1d.png)
2018117818 경영학부 김건희

**Comment by Jung-Jaemin** [comment]
![캡처](https://user-images.githubusercontent.com/71073008/97299123-d0f86480-1897-11eb-95ab-68e70f7845ae.PNG)
2016116453 정재민

**Comment by iougou03** [comment]
![image](https://user-images.githubusercontent.com/53176902/97367175-0038c100-18ec-11eb-9bf7-71334dc3efa9.png)

2017116948 글솦 권해솔

**Comment by kayoung0** [comment]
<img width="960" alt="파이썬3주차과제" src="https://user-images.githubusercontent.com/68316096/97801039-332cdd00-1c7d-11eb-8353-d506dba87e63.png">
2019113963 컴퓨터학부 김가영

**Comment by Qad00** [comment]
2020111177 글솦 카드리딘 
![SmartSelectImage_2020-11-02-18-54-49](https://user-images.githubusercontent.com/68487045/97855690-7733e680-1d3e-11eb-86b6-5605e195dd07.png)

**Comment by sseo512** [comment]
![image](https://user-images.githubusercontent.com/71762326/97883024-b1fe4480-1d67-11eb-8418-484d912e8d6c.png)
2019111509 전자공학부 서혜원

**Comment by hdddhdd** [comment]
2020114670 글로벌SW융합전공 최희정
![해달 python3주차](https://user-images.githubusercontent.com/71762328/97952374-7bb0db80-1de0-11eb-9448-6b1b70844477.PNG)

**Comment by johm3801** [comment]
과제 예시 답안입니다.
![1](https://user-images.githubusercontent.com/67828575/97952770-d8f95c80-1de1-11eb-955a-0ec70f588168.png)
![2](https://user-images.githubusercontent.com/67828575/97952772-da2a8980-1de1-11eb-83cb-036760db9231.png)

**Comment by kiryanchi** [comment]
![image](https://user-images.githubusercontent.com/50714602/97958842-6b552c80-1df1-11eb-9be5-440236dfe5fb.png)
2017112387 전자공학부 박기현

**Comment by jungnasm** [comment]
![F060B79A-05A8-4BB8-B835-BB10BAC5D3A9](https://user-images.githubusercontent.com/71762334/97967066-0d7c1100-1e00-11eb-800b-3b4b9996c4f6.jpeg)
2020114246 전자공학부 정상민

**Comment by penguin123-pi** [comment]
2019113608 전자공학부 이현중
![3주차 파이썬 과제](https://user-images.githubusercontent.com/71762382/97975754-ec6ded00-1e0c-11eb-935f-65e2e84e6761.PNG)

**Comment by yxxniverse** [comment]
2019113288 컴퓨터학부 서정윤
![캡처](https://user-images.githubusercontent.com/71762611/97987946-7b840080-1e1f-11eb-8df2-59e52f599f6c.JPG)

**Comment by bgainal** [comment]
2020111485 전자공학부 신영진
![image](https://user-images.githubusercontent.com/67634450/97990531-6dd07a00-1e23-11eb-94b6-cc2884a6e380.png)

**Comment by swimmmmie** [comment]
2019110667 컴퓨터학부 김수영
#
![SmartSelectImage_2020-11-04-00-57-40](https://user-images.githubusercontent.com/71762327/98009485-ee4da580-1e38-11eb-8312-e2b915b9fc98.png)

**Comment by m1-oh** [comment]
2017112219 전자공학부 오명원
![과제](https://user-images.githubusercontent.com/71762337/98032558-878bb480-1e57-11eb-82bd-1c2e51ccf98e.PNG)

**Comment by baha1909** [comment]
2020116142 모바일공학과 최인표
<img width="960" alt="해달 week3" src="https://user-images.githubusercontent.com/71762339/98060968-42cf4000-1e8e-11eb-8733-70b5b76211e9.png">

**Comment by MyNameIsTaeYeong** [comment]
2018117677 전자공학부 임태영
<img width="1440" alt="스크린샷 2020-11-04 오전 11 48 05" src="https://user-images.githubusercontent.com/38356853/98063674-e5d68880-1e93-11eb-88aa-e0ebef312028.png">

**Comment by DonggyuL** [comment]
전자공학부 이동규 2020112773
![해달 3주차hw](https://user-images.githubusercontent.com/71762567/98069462-305f0180-1ea2-11eb-9228-316e782d9067.PNG)

**Comment by gyeongpyo** [comment]
2018117630 컴퓨터학부 옥경표
![image](https://user-images.githubusercontent.com/29732273/98069597-7d42d800-1ea2-11eb-8d5a-3466950e9a6e.png)

**Comment by jeonghyeon1120** [comment]
![그림1](https://user-images.githubusercontent.com/72405201/98074420-c64c5980-1ead-11eb-8b95-5cd7cb74797a.png)
![그림2](https://user-images.githubusercontent.com/72405201/98074428-c9474a00-1ead-11eb-8ca3-787a0e1adea7.png)

**Comment by jeonghyeon1120** [comment]
![image](https://user-images.githubusercontent.com/72405201/98074631-217e4c00-1eae-11eb-91bb-972a2609c4d6.png)
![image](https://user-images.githubusercontent.com/72405201/98074645-29d68700-1eae-11eb-87af-4d5ee3f6188c.png)

**Comment by poseriang** [comment]
<img width="1034" alt="해달과제" src="https://user-images.githubusercontent.com/71762069/98081803-18e04280-1ebb-11eb-9465-18e2bfd0798b.png">
2020115194 전자공학부 민주호

**Comment by kimhj98** [comment]
![제목 없음](https://user-images.githubusercontent.com/41219623/98084038-90fc3780-1ebe-11eb-9e66-43611381b4b9.png)
2017110092 전자공학부 김현준

**Comment by ftlghk** [comment]
2020111501 전자 F 류시화
<img width="935" alt="1" src="https://user-images.githubusercontent.com/72428142/98084243-dfa9d180-1ebe-11eb-97de-c08381170fca.PNG">
<img width="941" alt="2" src="https://user-images.githubusercontent.com/72428142/98084258-e59fb280-1ebe-11eb-87e3-ea35eaa2db0a.PNG">

**Comment by packsooan** [comment]
2020113105 전자F 백수안
<img width="939" alt="캡처 PNG1" src="https://user-images.githubusercontent.com/71774889/98085280-6dd28780-1ec0-11eb-8c69-5e733c2d4ed0.PNG">
<img width="936" alt="캡처" src="https://user-images.githubusercontent.com/71774889/98085285-6f03b480-1ec0-11eb-8d02-45b0b6862091.PNG">

**Comment by Sungbinbinbin** [comment]
2020114669 전자공학부 조성빈
![image](https://user-images.githubusercontent.com/72425644/98092777-69ab6780-1eca-11eb-8860-cf19c1bf4ac5.png)

**Comment by Sungbinbinbin** [comment]
2020114669 전자공학부 조성빈
![image01](https://user-images.githubusercontent.com/72425644/98092925-96f81580-1eca-11eb-883d-f15dc07de0e6.png)

**Comment by himodu** [comment]
2020112267 컴퓨터학부 이동건입니다.
![zvfsdg](https://user-images.githubusercontent.com/71763322/98260622-e3c11680-1fc6-11eb-9d8b-f447a1d8e530.PNG)
![해달3주차파이썬과제](https://user-images.githubusercontent.com/71763322/98260638-e6bc0700-1fc6-11eb-850a-7231c607e567.PNG)

**Comment by choimyungbin** [comment]
2020111799 컴퓨터학부 최명빈입니다.

![2020-11-06 (1)](https://user-images.githubusercontent.com/71762087/98284198-1b8a8700-1fe4-11eb-821f-a4240d701de8.png)
![2020-11-06 (2)](https://user-images.githubusercontent.com/71762087/98284201-1cbbb400-1fe4-11eb-8118-9b04ca7220b1.png)

**Comment by choimyungbin** [comment]
2020111799 컴퓨터학부 최명빈입니다.
![Uploading 2020-11-06 (3).png…]()

**Comment by choimyungbin** [comment]
2020111799 컴퓨터학부 최명빈입니다.
![2020-11-06 (3)](https://user-images.githubusercontent.com/71762087/98286051-be440500-1fe6-11eb-9a5f-ea71b6237165.png)

**Comment by boksuh** [comment]
2017115698 전자공학부 서보경입니다.

![Screenshot 2020-11-07 204140](https://user-images.githubusercontent.com/71855057/98440091-ded0a400-2139-11eb-94c4-c216bcdcef18.jpg)

**Comment by cyj-aws** [comment]
202011367 전자공학부 진채영입니다
![image](https://user-images.githubusercontent.com/72435220/102290046-85069980-3f83-11eb-8d5a-5a516d36cb31.png)

**Comment by yeji-jeong** [comment]
![image](https://user-images.githubusercontent.com/71762325/102358932-7c4dac00-3ff3-11eb-914e-42fcf489ad33.png)

전자공학부 2019110481 정예지

**Comment by yanghuijin1214** [comment]
![pythonProject – 3 py 2020-12-16 오후 11_40_51](https://user-images.githubusercontent.com/57666289/102363064-67bfe280-3ff8-11eb-980a-9520981004b4.png)
컴퓨터학부 2018111062 양희진

**Comment by kimjea1999** [comment]
![SCR](https://user-images.githubusercontent.com/62633712/102457318-e4e56900-4085-11eb-9254-88992189ec56.png)
2019111569 컴퓨터학부 김지은

**Comment by hai-ley** [comment]
<img width="960" alt="2020-12-17 (9)" src="https://user-images.githubusercontent.com/71762106/102492698-67395180-40b5-11eb-9c7f-3737d324eb48.png">
<img width="960" alt="2020-12-17 (8)" src="https://user-images.githubusercontent.com/71762106/102492700-69031500-40b5-11eb-99eb-4dc8abdbddb0.png">

2020111179 전자공학부 장혜원

**Comment by hai-ley** [comment]
<img width="960" alt="2020-12-17 (8)" src="https://user-images.githubusercontent.com/71762106/102492766-80420280-40b5-11eb-9403-ee59aad41fa4.png">
<img width="960" alt="2020-12-17 (9)" src="https://user-images.githubusercontent.com/71762106/102492779-83d58980-40b5-11eb-9bfd-e0fde163ea22.png">

2020111179 전자공학부 장혜원
