### ISSUE TITLE
2020 2학기 파이썬 5주차 과제 제출

### ISSUE THREAD

**Issue by LJBang** [haedal-with-knu/theBeginingOfPython#30]
5주차에서 배운 csv모듈 실습을 사용하여 현재 듣고있는 강의들의 
코드, 강의명, 교수님, 학점(1학점/2학점/3학점)을 csv파일에 저장하고
코드와 csv파일의 내용을 캡쳐하여 제출해주세요!

**Comment by chadata** [comment]
![해달csv](https://user-images.githubusercontent.com/71762438/98834595-bb339380-2482-11eb-8c44-78e4944c03bf.JPG)
![해달코드](https://user-images.githubusercontent.com/71762438/98834612-bec71a80-2482-11eb-9db4-19973a97668b.JPG)

2018113598 모바일공학과 차민준

**Comment by iougou03** [comment]
![image](https://user-images.githubusercontent.com/53176902/98837648-8a555d80-2486-11eb-9e4b-997f859f3be5.png)

2017116948 글로벌 소프트웨어 융합과 권해솔

**Comment by kayoung0** [comment]
![py5코드](https://user-images.githubusercontent.com/68316096/98918612-2cba2300-2511-11eb-8129-1f279986808a.png)
![py5화면캡쳐](https://user-images.githubusercontent.com/68316096/98918624-30e64080-2511-11eb-8398-2422bf3780e9.png)
2019113963 컴퓨터학부 김가영

**Comment by DonggyuL** [comment]
전자공학부 이동규 2020112773
![해달 5주차 hw](https://user-images.githubusercontent.com/71762567/99075544-fe197680-25fc-11eb-9b9d-58b1842f0057.PNG)

**Comment by Jung-Jaemin** [comment]
![image](https://user-images.githubusercontent.com/71073008/99076110-f7d7ca00-25fd-11eb-97b4-1cb1c7484633.png)
2016116453 전자공학부 정재민

**Comment by kimhj98** [comment]
![image](https://user-images.githubusercontent.com/41219623/99134954-63a04e00-2663-11eb-996f-2d10d80a3408.png)

2017110092 전자공학부 김현준

**Comment by penguin123-pi** [comment]
![5주차 파이썬 과제(코드)](https://user-images.githubusercontent.com/71762382/99182952-bb31dd00-277b-11eb-9d68-4d2515df6bb2.PNG)
![5주차 파이썬 과제(csv파일)](https://user-images.githubusercontent.com/71762382/99182955-bd943700-277b-11eb-8525-61f00518c89f.PNG)

2019113608 전자공학부 이현중

**Comment by sseo512** [comment]
![5주차 과제](https://user-images.githubusercontent.com/71762326/99190650-0a433680-27ab-11eb-9d76-fe3bb245fd25.JPG)
![5주차 해달 과제 파일](https://user-images.githubusercontent.com/71762326/99190690-72921800-27ab-11eb-9b07-8c7610e1b39e.JPG)
2019111509 전자공학부 서혜원

**Comment by yanghuijin1214** [comment]
![해달과제](https://user-images.githubusercontent.com/57666289/99237558-fdbaee80-283b-11eb-907b-8e983f38eab1.JPG)
![해달과제1](https://user-images.githubusercontent.com/57666289/99237564-001d4880-283c-11eb-843e-886f98d3d68f.JPG)
2018111062 컴퓨터학부 양희진

**Comment by JMK1007** [comment]
![5주차](https://user-images.githubusercontent.com/67947887/99259174-f6f0a380-285c-11eb-9248-c9f2b2f14217.png)
2018117628 컴퓨터학부 김지민

**Comment by 52future** [comment]
컴퓨터학부 2020113825 손자영
![스크린샷(17)](https://user-images.githubusercontent.com/68419721/99338979-9f881d00-28c8-11eb-9f14-dbfdd39b3db6.png)

**Comment by boksuh** [comment]
2017115698 전자공학부 서보경
![python_week5](https://user-images.githubusercontent.com/71855057/99347349-41fccc00-28da-11eb-87fd-e40c47c325ef.jpg)

**Comment by hyeongjong98** [comment]
![image](https://user-images.githubusercontent.com/71762105/99348744-9fdee300-28dd-11eb-8230-c8fc3e3ff4be.png)

임산공학과 2017116463 이형종

**Comment by truegeonshow** [comment]
경영학과 2018117818 김건희
![image](https://user-images.githubusercontent.com/71762698/99352531-27305480-28e6-11eb-834a-a84e2f3736de.png)

**Comment by himodu** [comment]
2020112267 컴퓨터학부 이동건
![Uploading 5th_week.PNG…]()

**Comment by himodu** [comment]
![5th_week](https://user-images.githubusercontent.com/71763322/99357155-c8230d80-28ee-11eb-8856-c7a5f7d049db.PNG)
2020112267 컴퓨터학부 이동건

**Comment by yxxniverse** [comment]
![python_5](https://user-images.githubusercontent.com/71762611/99407955-017d6c80-2933-11eb-9e15-75aebf7b8f6b.JPG)
2019113288 컴퓨터학부 서정윤

**Comment by yeji-jeong** [comment]
![Uploading image.png…]()

**Comment by yeji-jeong** [comment]
2019110481정예지
<img width="960" alt="화면 캡처 2020-11-18 004842" src="https://user-images.githubusercontent.com/71762325/99412354-f842ce80-2937-11eb-8454-c1710edbb9b8.png">

**Comment by jeonghyeon1120** [comment]
![image](https://user-images.githubusercontent.com/72405201/99415300-021a0100-293b-11eb-8896-6340224b5ec6.png)

전자공학부 2019116357 나정현

**Comment by m1-oh** [comment]
![csv](https://user-images.githubusercontent.com/71762337/99472714-919bd000-298c-11eb-9c33-ea32a2670f7e.PNG)
![코드](https://user-images.githubusercontent.com/71762337/99472731-9791b100-298c-11eb-862a-c3d3884758c8.PNG)

2017112219 전자공학부 오명원

**Comment by MyNameIsTaeYeong** [comment]
<img width="1440" alt="스크린샷 2020-11-18 오전 11 33 28" src="https://user-images.githubusercontent.com/38356853/99475562-22c17580-2992-11eb-8140-4f1f28e8aee9.png">

2018117677 전자공학부 임태영

**Comment by poseriang** [comment]
![image](https://user-images.githubusercontent.com/71762069/99509483-291f1400-29c9-11eb-90e2-fd747427226c.png)
2020115194 전자공학부 민주호

**Comment by swimmmmie** [comment]
![image](https://user-images.githubusercontent.com/71762327/99549439-fc84ef80-29fc-11eb-8a3a-4ed5459c5177.png)
![image](https://user-images.githubusercontent.com/71762327/99549474-03abfd80-29fd-11eb-88d0-38124529fb4f.png)
2019110667 컴퓨터학부 김수영

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/46036377/101954899-3c2ba980-3c40-11eb-869b-6e6f2dbce27c.png)
![image](https://user-images.githubusercontent.com/46036377/101954927-48176b80-3c40-11eb-8f13-7e234894a2f5.png)
2020111799 컴퓨터학부 최명빈

**Comment by cyj-aws** [comment]
2020111367 전자공학부 진채영

![image](https://user-images.githubusercontent.com/72435220/102292007-af5a5600-3f87-11eb-9ff8-565c93e6f4ee.png)
![image](https://user-images.githubusercontent.com/72435220/102292018-b6816400-3f87-11eb-983c-052d222d19b2.png)

**Comment by hdddhdd** [comment]
![파이썬 5주차 과제](https://user-images.githubusercontent.com/71762328/102327468-1f3d0080-3fc9-11eb-9685-a6330be06e33.jpg)
2020114670 글로벌SW융합전공 최희정

**Comment by Qad00** [comment]
![SmartSelectImage_2020-12-17-05-15-11](https://user-images.githubusercontent.com/68487045/102401990-78d41800-4027-11eb-89cb-40b5644774c5.png)
2020111177 글솦 카드리딘

**Comment by kimjea1999** [comment]
![SCR01](https://user-images.githubusercontent.com/62633712/102455569-2d4f5780-4083-11eb-98b0-ed4a27907c33.png)
![SCR02](https://user-images.githubusercontent.com/62633712/102455584-304a4800-4083-11eb-8522-24ad2813174d.png)
2019111569 컴퓨터학부 김지은

**Comment by baha1909** [comment]
2020116142 모바일공학과 최인표
![Uploading image.png…]()

**Comment by baha1909** [comment]
2020116142 모바일공학과 최인표
<img width="960" alt="week5" src="https://user-images.githubusercontent.com/71762339/102483760-8978a280-40a8-11eb-8a85-fb5f83594535.png">

**Comment by hai-ley** [comment]
2020111179 전자공학부
<img width="960" alt="2020-12-17 (6)" src="https://user-images.githubusercontent.com/71762106/102489689-2d664c00-40b1-11eb-810d-8647ad27b5bb.png">
<img width="960" alt="2020-12-17 (4)" src="https://user-images.githubusercontent.com/71762106/102489694-2f300f80-40b1-11eb-9666-2fb993b3a5f3.png">

 장혜원

**Comment by hai-ley** [comment]
2020111179 전자공학부 장혜원
<img width="960" alt="2020-12-17 (4)" src="https://user-images.githubusercontent.com/71762106/102489731-3c4cfe80-40b1-11eb-943b-43862825a73b.png">
<img width="960" alt="2020-12-17 (6)" src="https://user-images.githubusercontent.com/71762106/102489736-3e16c200-40b1-11eb-8799-dc8dade33ce6.png">
