### ISSUE TITLE
2020 2학기 파이썬 6주차 과제 제출

### ISSUE THREAD

**Issue by SH0909** [haedal-with-knu/theBeginingOfPython#31]
아무 사이트에서 아무 내용이나 크롤링 해서 (자유!) cvs 파일에 저장 후 캡쳐 화면을 제출해주세요~~
ex ) 우리 학과 공지사항 제목과 작성자등등...

**Comment by chadata** [comment]
![파이썬 6주차](https://user-images.githubusercontent.com/71762438/99800582-f1a29a00-2b77-11eb-967d-318c5f39bfc5.JPG)

모바일공학과 2018113598 차민준

**Comment by iougou03** [comment]
![image](https://user-images.githubusercontent.com/53176902/99827870-8bc90900-2b9d-11eb-9832-eed3e1062d06.png)


 글로벌 소프트웨어 융합과 2017116948 권해솔
https://github.com/iougou03/Python-HaeDal/tree/master/Crawling

**Comment by kayoung0** [comment]
![movie_rank](https://user-images.githubusercontent.com/68316096/99878415-896fb900-2c48-11eb-8356-7704298c283e.png)
컴퓨터학부 2019113963 김가영
https://github.com/kayoung0/haedal-python

**Comment by JMK1007** [comment]
![6주차](https://user-images.githubusercontent.com/67947887/99878830-82967580-2c4b-11eb-8189-a1e363f870b4.png)
컴퓨터학부 2018117628 김지민

**Comment by DonggyuL** [comment]
2020112773 전자공학부 이동규

![해달 6주차 hw](https://user-images.githubusercontent.com/71762567/99881700-8ed7fe00-2c5e-11eb-828d-e865599ea231.PNG)

**Comment by boksuh** [comment]
2017115698 전자공학부 서보경
![python_screenshot](https://user-images.githubusercontent.com/71855057/99907090-26505600-2d1e-11eb-99ed-5505da8df87f.jpg)

**Comment by penguin123-pi** [comment]
2019113608 전자공학부 이현중
![6주차 파이썬 과제](https://user-images.githubusercontent.com/71762382/99910091-7edc1f00-2d2f-11eb-94f7-0a96ad243ebb.PNG)

**Comment by kimhj98** [comment]
2017110092 전자공학부 김현준
![image](https://user-images.githubusercontent.com/41219623/99959441-5e16d680-2dce-11eb-8009-e5000922c0c6.png)

**Comment by truegeonshow** [comment]
![image](https://user-images.githubusercontent.com/71762698/100073763-42b8d380-2e81-11eb-9b1a-8d037e26252b.png)
2018117818 경영학부 김건희

**Comment by himodu** [comment]
![sdfsaggg](https://user-images.githubusercontent.com/71763322/100131130-fbedcc80-2ec6-11eb-9944-eed290fe5a01.PNG)
2020112267 컴퓨터학부 이동건

**Comment by yanghuijin1214** [comment]
![csv파일](https://user-images.githubusercontent.com/57666289/100141057-23e42c80-2ed5-11eb-863f-186d27a78884.JPG)
2018111062 컴퓨터학부 양희진

**Comment by kiryanchi** [comment]
![image](https://user-images.githubusercontent.com/50714602/100164975-6e2cd400-2efc-11eb-82d9-443520358f9f.png)
2017112387 전자공학부 박기현

**Comment by sseo512** [comment]
![6주차 해달 과제](https://user-images.githubusercontent.com/71762326/100165387-82250580-2efd-11eb-8d04-26f63d82e94c.JPG)
2019111509 전자공학부 서혜원

**Comment by hyeongjong98** [comment]
![image](https://user-images.githubusercontent.com/71762105/100173544-15663700-2f0e-11eb-9690-143a056e244c.png)
2017116463 이형종

**Comment by swimmmmie** [comment]
![image](https://user-images.githubusercontent.com/71762327/100180620-e0f97780-2f1b-11eb-9968-2ad6ad1668a7.png)
2019110667 컴퓨터학부 김수영

**Comment by bgainal** [comment]
![image](https://user-images.githubusercontent.com/67634450/100181946-c1178300-2f1e-11eb-97ad-e879515aab17.png)
2020111485 전자공학부 신영진

**Comment by 52future** [comment]
2020113825 컴퓨터학부 손자영
![스크린샷(20)](https://user-images.githubusercontent.com/68419721/100182058-0dfb5980-2f1f-11eb-9573-73860b1b75ca.png)

**Comment by yeji-jeong** [comment]
전자공학부 2019110481 정예지
![image](https://user-images.githubusercontent.com/71762325/100184457-e3ac9a80-2f24-11eb-8373-9ceb9cc2bbd1.png)

**Comment by yeji-jeong** [comment]
2019110481 정예지
![image](https://user-images.githubusercontent.com/71762325/100184517-05a61d00-2f25-11eb-82fc-ba2bcfebdca9.png)

**Comment by choimyungbin** [comment]
![image](https://user-images.githubusercontent.com/71762087/101993507-925f2200-3cfe-11eb-831b-3ff88cfbefb0.png)
2020111799 컴퓨터학부 최명빈

**Comment by cyj-aws** [comment]
2020111367 전자공학부 진채영

![image](https://user-images.githubusercontent.com/72435220/102293501-9901c980-3f8a-11eb-8640-58d811e0257e.png)

**Comment by yxxniverse** [comment]
2019113288 컴퓨터학부 서정윤
![python_6](https://user-images.githubusercontent.com/71762611/102321004-6ffc2b80-3fc0-11eb-9366-8c00ce47657e.JPG)

**Comment by yxxniverse** [comment]
![python_6](https://user-images.githubusercontent.com/71762611/102322538-90c58080-3fc2-11eb-8241-d71598cccbfa.jpg)

2019113288 컴퓨터학부 서정윤
