### ISSUE TITLE
2020 2학기 파이썬 7주차 과제 제출

### ISSUE THREAD

**Issue by johm3801** [haedal-with-knu/theBeginingOfPython#32]
플라스크로 웹서버 띄우는 과제입니다. 

http://127.0.0.1:5000/ 로 접속 시 자기 학번, 학과, 이름 출력
http://127.0.0.1:5000/me 로 접속 시 자신과 관련된 이미지 출력

스크린샷 두 장 찍어서 제출해주세요.

**Comment by chadata** [comment]
![해달과제1](https://user-images.githubusercontent.com/71762438/100230630-4aec3e00-2f69-11eb-9bc6-6450be6fadfc.JPG)
![해달과제2](https://user-images.githubusercontent.com/71762438/100230648-50498880-2f69-11eb-8c39-fd38669d43cd.JPG)
2018113598 모바일공학과 차민준

**Comment by kimhj98** [comment]
![image](https://user-images.githubusercontent.com/41219623/100366862-b9ea9500-3044-11eb-9ff3-a960e26c5dc1.png)
![image](https://user-images.githubusercontent.com/41219623/100369082-c9b7a880-3047-11eb-9141-d1f82f762f30.png)

2017110092 전자공학부 김현준

**Comment by iougou03** [comment]
![image](https://user-images.githubusercontent.com/53176902/100551749-10b2d180-32c6-11eb-9518-0e0f36b41207.png)

2017116948 글솦 권해솔

**Comment by boksuh** [comment]
![result1](https://user-images.githubusercontent.com/71855057/100569626-f56db380-3311-11eb-9e55-1cdf4cb27229.jpg)
![result2](https://user-images.githubusercontent.com/71855057/100569630-f69ee080-3311-11eb-9fe6-34483b65a9b3.jpg)

2017115698 전자공학부 서보경

**Comment by JMK1007** [comment]
![week07_1](https://user-images.githubusercontent.com/67947887/100591346-f49c4800-3338-11eb-924c-77cb67b63961.png)
![week07_2](https://user-images.githubusercontent.com/67947887/100591352-f6fea200-3338-11eb-9c99-bf80b77a63eb.png)
2018117628 컴퓨터학부 김지민

**Comment by truegeonshow** [comment]
![image](https://user-images.githubusercontent.com/71762698/100703393-cd03b900-33e6-11eb-9e04-10822091e52b.png)

![image](https://user-images.githubusercontent.com/71762698/100703361-b52c3500-33e6-11eb-9610-9ebe49e48af3.png)
2018117818 경영 김건희

**Comment by MyNameIsTaeYeong** [comment]
[
<img width="1440" alt="스크린샷 2020-12-01 오후 6 34 02" src="https://user-images.githubusercontent.com/38356853/100722335-dbac9900-3403-11eb-81e9-f3e53d2ca1af.png">
](url)

**Comment by yanghuijin1214** [comment]
![해달1](https://user-images.githubusercontent.com/57666289/100727269-59bf6e80-3409-11eb-9378-42cbee660714.JPG)
2018111062 컴퓨터학부 양희진

**Comment by swimmmmie** [comment]
![image](https://user-images.githubusercontent.com/71762327/100821306-72746680-3493-11eb-818c-3d2869d6bd94.png)
![image](https://user-images.githubusercontent.com/71762327/100822379-8620cc80-3495-11eb-8b7c-57b133241445.png)

2019110667 컴퓨터학부 김수영

**Comment by penguin123-pi** [comment]
![7주차 파이썬(1)](https://user-images.githubusercontent.com/71762382/101243555-94e0db00-3744-11eb-8d3a-27cab4f2446d.PNG)
![7주차 파이썬(2)](https://user-images.githubusercontent.com/71762382/101243557-97dbcb80-3744-11eb-9599-219c0d003d0b.PNG)

2019113608 이현중

**Comment by Jung-Jaemin** [comment]
![캡처](https://user-images.githubusercontent.com/71073008/101906997-3365b400-3bfd-11eb-8f28-fa34adfe0941.PNG)
![3](https://user-images.githubusercontent.com/71073008/101907192-8dff1000-3bfd-11eb-91bf-466a69f985f5.png)


2016116453정재민

**Comment by m1-oh** [comment]
2017112219 오명원
![1](https://user-images.githubusercontent.com/71762337/101932849-bcd9ae00-3c1e-11eb-92a1-16ba6c7e17e4.PNG)
![2](https://user-images.githubusercontent.com/71762337/101932868-c3682580-3c1e-11eb-8d24-97439885cdaf.PNG)

**Comment by kiryanchi** [comment]
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/50714602/101977284-f991bd80-3c8f-11eb-931a-488d3adebe36.png">
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/50714602/101977285-fd254480-3c8f-11eb-9610-f73f551705a0.png">

**Comment by poseriang** [comment]
![image](https://user-images.githubusercontent.com/71762069/101979467-a70ccd00-3ca0-11eb-9116-d1f3012d3b18.png)
![image](https://user-images.githubusercontent.com/71762069/101979809-a0338980-3ca3-11eb-8cb4-3f5d474e6d3a.png)

**Comment by hdddhdd** [comment]
![image](https://user-images.githubusercontent.com/71762328/102478951-980f8b80-40a1-11eb-8699-a848d9c97c9b.png)
2020114670 최희정
(해보고 있는데 잘 안돼서 일단 코드라도 제출합니다ㅠㅠ!!)

**Comment by Qad00** [comment]
![SmartSelectImage_2020-12-17-20-39-31](https://user-images.githubusercontent.com/68487045/102488837-ffccd300-40af-11eb-998e-f83b0fcce6a2.png)
![SmartSelectImage_2020-12-17-21-35-48](https://user-images.githubusercontent.com/68487045/102488843-00fe0000-40b0-11eb-89be-a413eabab6dc.png)
글솦 2020111177 카드리딘

**Comment by himodu** [comment]
![1111111111](https://user-images.githubusercontent.com/71763322/102489560-fa23bd00-40b0-11eb-8216-efd802daf3ec.PNG)
![525](https://user-images.githubusercontent.com/71763322/102489542-f42ddc00-40b0-11eb-9b05-c18ab7bb4990.PNG)

2020112267 컴퓨터학부 이동건

**Comment by hai-ley** [comment]
<img width="960" alt="2020-12-17 (10)" src="https://user-images.githubusercontent.com/71762106/102497174-aa96be80-40bb-11eb-9a6a-d28aaf667012.png">
![2020-12-17 (12)](https://user-images.githubusercontent.com/71762106/102497188-ae2a4580-40bb-11eb-88cc-27e0f321d101.jpg)

2020111179 전자공학부 장혜원

**Comment by hai-ley** [comment]
<img width="960" alt="2020-12-17 (10)" src="https://user-images.githubusercontent.com/71762106/102497244-bf735200-40bb-11eb-948c-201b2ce55bd7.png">
![2020-12-17 (12)](https://user-images.githubusercontent.com/71762106/102497259-c39f6f80-40bb-11eb-9a28-1a779a55e461.jpg)

2020111179 전자공학부 장혜원

**Comment by hai-ley** [comment]
<img width="960" alt="2020-12-17 (10)" src="https://user-images.githubusercontent.com/71762106/102497488-0c572880-40bc-11eb-963e-e1c1a7343476.png">
![2020-12-17 (12)](https://user-images.githubusercontent.com/71762106/102497510-124d0980-40bc-11eb-9272-1e9abb7cec14.jpg)

2020111179 전자공학부 장혜원

**Comment by hai-ley** [comment]
<img width="960" alt="2020-12-17 (10)" src="https://user-images.githubusercontent.com/71762106/102497887-93a49c00-40bc-11eb-8df0-316a25744a79.png">
<img width="960" alt="2020-12-17 (11)" src="https://user-images.githubusercontent.com/71762106/102497902-97d0b980-40bc-11eb-83f0-066c0dc8d4b5.png">

2020111179 전자공학부 장혜원
